### ISSUE TITLE
relicensing LLGPL → GPLv3

### ISSUE THREAD

**Issue by zzkt** [zzkt/osc#12]
Based on the discussion and analysis on [cliki](https://www.cliki.net/LLGPL) about the [LLGPL](https://www.cliki.net/LLGPL) (in particular [Eli Greenbaum's detailed examination of the LLGPL](https://www.ifosslr.org/index.php/ifosslr/article/view/75/146)) I think it makes sense to change the licence to GPLv3 (or later). 

If there is anyone who has contributed to the library that objects to this please let me know.

**Comment by zzkt** [comment]
cc @PuercoPop @boqs @erikronstrom @jamieforth

**Comment by PuercoPop** [comment]
@zzkt I'm always in favor of the strongest copyleft possible until the time IP is abolished. If anything I'd recommend AGPLv3! 👍
