### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [zzkt/osc#13]
Building with SBCL 2.2.7.28-02bc916fd / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id e46e9b1942c3bd5a439dceafa576c062a68c6cbd

*osc* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016C8003}>: The name "SB-BSD-SOCKETS" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2022-09-28/failure-report/osc.html)

**Comment by zzkt** [comment]
Thanks for picking this up @quicklisp I haven't looked closely at it for a while but made a few small changes which should improve things. What's the best way to test quicklisp builds currently?

**Comment by quicklisp** [comment]
It looks good now, thanks.

Best way would be to try to load it in bare sbcl (not in sly/slime or with
an extensive init file) with ASDF warnings visible. If using quickload, use
:verbose t as well.
